### ISSUE TITLE
Sign in with google and facebook pop-up can use but they are disappear after clicked.

### ISSUE THREAD

**Issue by Driveiei** [thanakritfluk/qoting#37]
After you fixed dummy button from #35 issue. I use Google Chrome to Sign in with google and facebook, but pop-up can't use. It's disappear(white frame in the picture below) with nothing after I clicked sign-in.
![image](https://user-images.githubusercontent.com/32285760/49369028-f2d82380-f722-11e8-934d-402f7def35e5.png)

**Comment by cynic4018** [comment]
Now, pop-up sign-in can't use in chrome, but it can use in Firefox and IE. Chrome is in maintaining.
